env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'import/prefer-default-export': off
  'import/extensions': off
  'import/no-unresolved': off
  'react/jsx-filename-extension':
    - error
    - extensions:
        - '.tsx'
  'react/react-in-jsx-scope': off
  'import/no-extraneous-dependencies':
    - off
    - extensions:
        - '.test.tsx'
